### ISSUE TITLE
wrong name in manifest.json

### ISSUE THREAD

**Issue by mixMugz** [egoroffse/kronshtadt#1]
UKRO (ULLI) Kronshtadt Airfield
вроде ULLY правильнее?

**Comment by egoroffse** [comment]
Спасибо! Исправим 👍

**Comment by egoroffse** [comment]
> UKRO (ULLI) Kronshtadt Airfield
> вроде ULLY правильнее?

Спасибо! Исправим 👍

**Comment by egoroffse** [comment]
> UKRO (ULLI) Kronshtadt Airfield
> вроде ULLY правильнее?

Исправлено в Master Branch Build
https://github.com/egoroffse/kronshtadt/archive/master.zip
и так же в новых релизах
